/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calcula_hipotecario_bravojosué;

import javax.swing.JOptionPane;

/**
 *
 * @author iryde
 */
public class AppSimuladorHipotecario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppSimuladorHipotecario.class.getName());

    /**
     * Creates new form AppSimuladorHipotecario
     */
    public AppSimuladorHipotecario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        Panel = new javax.swing.JPanel();
        lblValorPropiedad = new javax.swing.JLabel();
        txtValorPropiedad = new javax.swing.JTextField();
        lblAhorroPrevio = new javax.swing.JLabel();
        lblSueldoLiquido = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        cmbPlazoCredito = new javax.swing.JComboBox<>();
        lblPlazoCredito = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtSueldoLiquido = new javax.swing.JTextField();
        txtAhorroPrevio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador Hipotecario");

        Panel.setBackground(new java.awt.Color(0, 51, 102));

        lblValorPropiedad.setForeground(new java.awt.Color(255, 255, 255));
        lblValorPropiedad.setText("Valor de la propiedad (UF):");
        lblValorPropiedad.setToolTipText("");

        lblAhorroPrevio.setForeground(new java.awt.Color(255, 255, 255));
        lblAhorroPrevio.setText("Ahorro previo o Pie (UF):");
        lblAhorroPrevio.setToolTipText("");

        lblSueldoLiquido.setForeground(new java.awt.Color(255, 255, 255));
        lblSueldoLiquido.setText("Sueldo líquido mensual:");
        lblSueldoLiquido.setToolTipText("");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        cmbPlazoCredito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "20", "25", "30" }));

        lblPlazoCredito.setForeground(new java.awt.Color(255, 255, 255));
        lblPlazoCredito.setText("Plazo del crédito (años):");
        lblPlazoCredito.setToolTipText("");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Simulador Hipotecario");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(lblAhorroPrevio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAhorroPrevio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(lblSueldoLiquido)
                                .addGap(12, 12, 12)
                                .addComponent(txtSueldoLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCalcular)
                                    .addComponent(lblPlazoCredito))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbPlazoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(lblValorPropiedad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(65, 65, 65))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorPropiedad)
                    .addComponent(txtValorPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAhorroPrevio)
                    .addComponent(txtAhorroPrevio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSueldoLiquido)
                    .addComponent(txtSueldoLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlazoCredito)
                    .addComponent(cmbPlazoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {
            int valorPropiedad = Integer.parseInt(txtValorPropiedad.getText());
            int ahorroPrevio = Integer.parseInt(txtAhorroPrevio.getText());
            int sueldoLiquido = Integer.parseInt(txtSueldoLiquido.getText());
            int plazoCredito = Integer.parseInt(cmbPlazoCredito.getSelectedItem().toString());
            
            // Validar "valorPropiedad"
            if (valorPropiedad < 1500 || valorPropiedad > 5000) {
                JOptionPane.showMessageDialog(null, "El valor de la propiedad debe estar entre 1500 y 5000 UF.", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Validar "ahorroPrevio"
            if (ahorroPrevio <= 0) {
               JOptionPane.showMessageDialog(null, "El ahorro previo debe ser mayor a 0.", "", JOptionPane.INFORMATION_MESSAGE);
                return; 
            } else if (ahorroPrevio < valorPropiedad * 0.1) {
                JOptionPane.showMessageDialog(null, "Rechazado: El ahorro mínimo debe ser del 10%", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Validar "sueldoLiquido"
            if (sueldoLiquido <= 0) {
                JOptionPane.showMessageDialog(null, "El sueldo líquido debe ser mayor a 0.", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            // Instanciar clase "hipoteca"
            Hipoteca hipoteca_ = new Hipoteca(valorPropiedad, ahorroPrevio, sueldoLiquido, plazoCredito);
            
            if (hipoteca_.evaluarDirectamente()) { // Aprobación directa.
                JOptionPane.showMessageDialog(null, "Felicidades: Crédito Pre-Aprobado (Bajo riesgo)");
            } else {
                String resAval = JOptionPane.showInputDialog(null, "Ingrese el suelo líquido de un aval:");
                
                int sueldoAval = Integer.parseInt(resAval);
                
                if (hipoteca_.evaluarComplemento(sueldoAval)) { // Evaluación complemento.
                    JOptionPane.showMessageDialog(null, "Aprobado con Complemento de Renta");
                } else {
                    JOptionPane.showMessageDialog(null, "Rechazado. Capacidad de pago insuficiente");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese números válidos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppSimuladorHipotecario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cmbPlazoCredito;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel lblAhorroPrevio;
    private javax.swing.JLabel lblPlazoCredito;
    private javax.swing.JLabel lblSueldoLiquido;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorPropiedad;
    private javax.swing.JTextField txtAhorroPrevio;
    private javax.swing.JTextField txtSueldoLiquido;
    private javax.swing.JTextField txtValorPropiedad;
    // End of variables declaration//GEN-END:variables
}
