/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author iryde
 */
import java.sql.*;
import javax.swing.JOptionPane;

public class AppIncidente extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppIncidente.class.getName());

    /**
     * Creates new form AppDatos
     */
    public AppIncidente() {
        initComponents();

        cargarContinentes();
        cargarPaises();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JOption = new javax.swing.JOptionPane();
        Panel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtHeadOfState = new javax.swing.JTextField();
        lblHeadOfState = new javax.swing.JLabel();
        lblContinente = new javax.swing.JLabel();
        cmbContinente = new javax.swing.JComboBox<>();
        lblPais = new javax.swing.JLabel();
        cmbPais = new javax.swing.JComboBox<>();
        lblPopulation = new javax.swing.JLabel();
        txtPopulation = new javax.swing.JTextField();
        lblLifeExpectancy = new javax.swing.JLabel();
        txtLifeExpectancy = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Datos Geográficos");

        lblHeadOfState.setText("Presidente:");

        lblContinente.setText("Continente:");

        cmbContinente.addActionListener(this::cmbContinenteActionPerformed);

        lblPais.setText("País:");

        cmbPais.addActionListener(this::cmbPaisActionPerformed);

        lblPopulation.setText("Población:");

        txtPopulation.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblLifeExpectancy.setText("Esperanza de vida (años):");

        btnModificar.setText("Modificar datos");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnModificar))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(lblHeadOfState)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHeadOfState, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addComponent(lblLifeExpectancy)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtLifeExpectancy))
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addComponent(lblPopulation)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblContinente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbContinente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lblPais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(106, 106, 106))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContinente)
                    .addComponent(cmbContinente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPais)
                    .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPopulation)
                    .addComponent(txtPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLifeExpectancy)
                    .addComponent(txtLifeExpectancy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeadOfState)
                    .addComponent(txtHeadOfState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void cmbContinenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbContinenteActionPerformed
        cargarPaises();
    }//GEN-LAST:event_cmbContinenteActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ConectorBD conector = null;

        try {
            conector = new ConectorBD();

            String Population = txtPopulation.getText();
            String LifeExpectancy = txtLifeExpectancy.getText();
            String HeadOfState = txtHeadOfState.getText();

            String Pais = cmbPais.getSelectedItem().toString();

            if (Population.equals("") && LifeExpectancy.equals("") && HeadOfState.equals("")) {
                JOptionPane.showMessageDialog(null, "Primero cargue los datos para modificarlos");
                return;
            }

            int cantidad = conector.modificar("UPDATE Country SET Population = ?, LifeExpectancy = ?, HeadOfState = ?  WHERE Name = ?", Population, LifeExpectancy, HeadOfState, Pais);

            if (cantidad > 0) {
                JOptionPane.showMessageDialog(null, "Los datos fueron actualizados exitosamente");
            } else {
                JOptionPane.showMessageDialog(null, "No se hicieron cambios.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (conector != null) {
                    conector.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cmbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaisActionPerformed
        if (cmbPais.getSelectedItem() == null) {
            return;
        }

        String pais = cmbPais.getSelectedItem().toString();

        ConectorBD conector = null;

        try {
            conector = new ConectorBD();

            ResultSet rs = conector.consultar("SELECT Population, LifeExpectancy, HeadOfState FROM Country WHERE Name = ?", pais);

            if (rs.next()) {
                txtPopulation.setText(rs.getString("Population"));
                txtLifeExpectancy.setText(rs.getString("LifeExpectancy"));
                txtHeadOfState.setText(rs.getString("HeadOfState"));
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron elementos");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (conector != null) {
                    conector.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_cmbPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppIncidente().setVisible(true));
    }

    private void cargarContinentes() {
        ConectorBD conector = null;

        try {
            conector = new ConectorBD();

            ResultSet rs = conector.consultar("SELECT DISTINCT Continent FROM country ORDER BY Continent");

            while (rs.next()) {
                cmbContinente.addItem(rs.getString("Continent"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (conector != null) {
                    conector.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }

    private void cargarPaises() {
        ConectorBD conector = null;

        try {
            conector = new ConectorBD();

            cmbPais.removeAllItems();
            String Continent = cmbContinente.getSelectedItem().toString();

            ResultSet rs = conector.consultar("SELECT Name FROM country WHERE Continent = ? ORDER BY Name", Continent);

            while (rs.next()) {
                cmbPais.addItem(rs.getString("Name"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (conector != null) {
                    conector.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane JOption;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbContinente;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblContinente;
    private javax.swing.JLabel lblHeadOfState;
    private javax.swing.JLabel lblLifeExpectancy;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPopulation;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtHeadOfState;
    private javax.swing.JTextField txtLifeExpectancy;
    private javax.swing.JTextField txtPopulation;
    // End of variables declaration//GEN-END:variables

}
