/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InsertaCity_BravoJosue;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author iryde
 */
public final class App extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(App.class.getName());

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        cargarPaises(); // Carga la lista de paises al iniciar la aplicación.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        lblPais = new javax.swing.JLabel();
        cmbPais = new javax.swing.JComboBox<>();
        lblCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lblPoblacion = new javax.swing.JLabel();
        txtPoblacion = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        lblDistrito = new javax.swing.JLabel();
        cmbDistrito = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPais.setText("País:");

        cmbPais.addActionListener(this::cmbPaisActionPerformed);

        lblCiudad.setText("Ciudad:");

        lblPoblacion.setText("Población:");

        btnInsertar.setText("Insertar ciudad");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        lblDistrito.setText("Distrito:");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(lblCiudad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCiudad))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addComponent(lblPais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(lblPoblacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsertar)
                            .addComponent(txtPoblacion)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(lblDistrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPais)
                    .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistrito)
                    .addComponent(cmbDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudad)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPoblacion)
                    .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnInsertar)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new App().setVisible(true));
    }

    private void cmbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaisActionPerformed
        String codigoPais = obtenerCodigo(); // Llama a la función que devuelve el código del país.
        cmbDistrito.removeAllItems(); // Elimina los datos anteriores del combobox.

        try {
            Conector conector = new Conector(); // Llamada a la clase para establecer la conexión con la BD.

            ResultSet rs = conector.consultar("SELECT DISTINCT(District) FROM City WHERE CountryCode = ?", codigoPais); // Consulta SQL que devuelve los distritos sin duplicados de cada ciudad del país especificado con su código de páis.

            while (rs.next()) { // Recorre mientras hayan datos.
                cmbDistrito.addItem(rs.getString("District")); // Añade cada nombre del distrito al combobox.
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "SQL ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmbPaisActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            String codigoPais = obtenerCodigo(); // Llama a la función que devuelve el código del país.
            String ciudad = txtCiudad.getText(); // Obtiene la ciudad ingresada por el usuario.
            String distrito = cmbDistrito.getSelectedItem().toString(); // Obtiene el distrito seleccionado del combobox.
            int poblacion = Integer.parseInt(txtPoblacion.getText()); // Obtiene la población ingresada por el usuario y la convierte a un número entero.

            if (ciudad.equals("")) { // Valida que la ciudad ingresada no se encuentre vacía.
                JOptionPane.showMessageDialog(null, "Debe ingresar una ciudad", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (poblacion <= 0) { // Valida que la población ingresada no sea menor o igual a 0
                JOptionPane.showMessageDialog(null, "Debe ingresar una población mayor a 0", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Conector conector = new Conector(); // Llamada a la clase para establecer la conexión con la BD.

            int filas = conector.modificar("INSERT INTO city (Name, CountryCode, District, Population) VALUES (?, ?, ?, ?)", ciudad, codigoPais, distrito, poblacion);

            if (filas > 0) { // Valida que la cantidad de filas actualizadas sea mayor a 0 (>= 1).
                JOptionPane.showMessageDialog(null, "Se actualizaron los datos", "Mensaje", JOptionPane.PLAIN_MESSAGE);
            } else { // Si no se modificaron filas.
                JOptionPane.showMessageDialog(null, "No se hicieron cambios", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) { // Valida que si se ingresa texto o algo inválido en el campo de números lance una excepción.
            JOptionPane.showMessageDialog(null, "Ingrese un número válido", "Número", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "SQL ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    /**
     * @author Josué Bravo
     * @since 12-06-2026
     * @version 1.0.0
     * @exception java.sql.SQLException
     * @see Conector Clase que es la encargada de establecer la conexión con la base de datos y hacer las consultas.
     * Función encargada de cargar la lista de paises y agregarlas a la lista (combobox).
     */
    public void cargarPaises() { // Función para cargar la lista de paises.
        try {
            Conector conector = new Conector(); // Llamada a la clase para establecer la conexión con la BD.

            ResultSet rs = conector.consultar("SELECT Name FROM Country ORDER BY Name"); // Consulta SQL que devuelve el nombre del país y lo ordena de A-Z.

            while (rs.next()) { // Recorre mientras hayan datos.
                cmbPais.addItem(rs.getString("Name")); // Añade cada nombre del país al combobox.
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Carga de paises (SQL ERROR)", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * @author Josué Bravo
     * @since 12-06-2026
     * @version 1.0.0
     * @return Retorna el código del país seleccionado o un texto vació si ocurrió un error.
     * @exception java.sql.SQLException
     * @see Conector Clase que es la encargada de establecer la conexión con la base de datos y hacer las consultas.
     * Función encargada de entregar el código de un país seleccionado.
     */
    public String obtenerCodigo() { // Función para obtener el código del país seleccionado (ej. CHL)
        if (cmbPais.getSelectedItem() == null) { // Validar que el item en cmbPais no sea nulo por alguna razón, al inicio del programa tal vez.
            return "";
        }

        String pais = cmbPais.getSelectedItem().toString(); // Obtiene el país seleccionado y lo convierte a texto.

        try {
            Conector conector = new Conector(); // Llamada a la clase para establecer la conexión con la BD.

            ResultSet rs = conector.consultar("SELECT Code FROM Country WHERE Name = ?", pais); // Consulta SQL que devuelve el código del país, pasando como argumento el nombre del país.

            if (rs.next()) { // Verifica que hay datos
                return rs.getString("Code"); // Retorna el código del país.
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Código de país (SQL ERROR)", JOptionPane.WARNING_MESSAGE);
        }

        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JComboBox<String> cmbDistrito;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDistrito;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPoblacion;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtPoblacion;
    // End of variables declaration//GEN-END:variables
}
