/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visorworld_bravojosue;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 * Programa "VisorWorld" que permite consultar las ciudades de un país
 * seleccionado, además de agregar ciudades y su respectiva población a un
 * distrito seleccionado.
 *
 * @author Josué Bravo
 */
public class App extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(App.class.getName());

    /**
     * Crea la ventana principal de VisorWorld e inicializa los combobox cmbPais
     * y cmbDistrito con todos los países y distritos de Chile disponibles en la base
     * de datos.
     */
    public App() {
        initComponents();
        cargarPaises();
        cargarDistritosCHL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JOptionPane = new javax.swing.JOptionPane();
        TabbedPane = new javax.swing.JTabbedPane();
        pnlConsultar = new javax.swing.JPanel();
        cmbPais = new javax.swing.JComboBox<>();
        lblPais = new javax.swing.JLabel();
        ScrollPanel = new javax.swing.JScrollPane();
        tbCiudades = new javax.swing.JTable();
        pnlRegistrar = new javax.swing.JPanel();
        lblDistrito = new javax.swing.JLabel();
        cmbDistrito = new javax.swing.JComboBox<>();
        lblCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lblPoblacion = new javax.swing.JLabel();
        txtPoblacion = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        miArchivo = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();
        miConsultas = new javax.swing.JMenu();
        miConsultar = new javax.swing.JMenuItem();
        miRegistrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestor World");

        TabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        cmbPais.addActionListener(this::cmbPaisActionPerformed);

        lblPais.setText("País:");

        tbCiudades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ScrollPanel.setViewportView(tbCiudades);

        javax.swing.GroupLayout pnlConsultarLayout = new javax.swing.GroupLayout(pnlConsultar);
        pnlConsultar.setLayout(pnlConsultarLayout);
        pnlConsultarLayout.setHorizontalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarLayout.createSequentialGroup()
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblPais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addGroup(pnlConsultarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlConsultarLayout.setVerticalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Consultar", pnlConsultar);

        lblDistrito.setText("Distrito:");

        lblCiudad.setText("Ciudad:");

        lblPoblacion.setText("Población:");

        btnInsertar.setText("Insertar ciudad");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        javax.swing.GroupLayout pnlRegistrarLayout = new javax.swing.GroupLayout(pnlRegistrar);
        pnlRegistrar.setLayout(pnlRegistrarLayout);
        pnlRegistrarLayout.setHorizontalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDistrito)
                    .addComponent(lblCiudad)
                    .addComponent(lblPoblacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRegistrarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnInsertar)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        pnlRegistrarLayout.setVerticalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistrito)
                    .addComponent(cmbDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudad)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPoblacion)
                    .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsertar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Registrar", pnlRegistrar);

        miArchivo.setText("Archivo");

        miSalir.setText("Salir");
        miSalir.addActionListener(this::miSalirActionPerformed);
        miArchivo.add(miSalir);

        MenuBar.add(miArchivo);

        miConsultas.setText("Ver");

        miConsultar.setText("Consultar");
        miConsultar.addActionListener(this::miConsultarActionPerformed);
        miConsultas.add(miConsultar);

        miRegistrar.setText("Registrar");
        miRegistrar.addActionListener(this::miRegistrarActionPerformed);
        miConsultas.add(miRegistrar);

        MenuBar.add(miConsultas);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        this.dispose(); // Función de java para cerrar el programa.
    }//GEN-LAST:event_miSalirActionPerformed

    DefaultTableModel mt = new DefaultTableModel(); // Se instancia el DefaultTableModel (Modelo de tabla?)
    private void cmbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaisActionPerformed
        mt.setRowCount(0); // Se elimina todas las filas de la tabla, esto para que al seleccionar otro país se borren las filas que ya estén.

        String pais = obtenerCodigoPais(); // Se llama a la función que devuelve el código del país seleccionado.

        String columnas[] = {"ID", "Nombre", "País", "Distrito", "Población"}; // Se crea un arreglo que almacena los encabezados de cada columna.
        mt.setColumnIdentifiers(columnas); // Se añaden al modelo de la tabla instanciado anteriormente.
        tbCiudades.setModel(mt); // Se agrega el modelo a la tabla de Ciudades.

        try {
            Conector conector = new Conector(); // Se instancia la clase que establece la conexión con la base de datos.

            ResultSet rs = conector.consultar("SELECT ID, Name, CountryCode, District, Population FROM city WHERE CountryCode = ? ORDER BY Name", pais);

            while (rs.next()) { // Recorre los resultados mientra haya datos.
                mt.addRow(new Object[]{
                    rs.getString("ID"),
                    rs.getString("Name"),
                    rs.getString("CountryCode"),
                    rs.getString("District"),
                    rs.getString("Population")
                }); // Se van agregando filas con los datos.
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Carga de ciudades (SQL ERROR)", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmbPaisActionPerformed

    private void miConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarActionPerformed
        TabbedPane.setSelectedComponent(pnlConsultar); // Cambia la vista a la de "Consultar".
    }//GEN-LAST:event_miConsultarActionPerformed

    private void miRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistrarActionPerformed
        TabbedPane.setSelectedComponent(pnlRegistrar); // Cambia la vista a la de "Registrar".
    }//GEN-LAST:event_miRegistrarActionPerformed

    /**
     * Botón para insertar la ciudad ingresada por el usuario.
     */
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        String ciudad = txtCiudad.getText(); // Se obtiene la ciudad ingresada.
        String distrito = cmbDistrito.getSelectedItem().toString(); // Se obtiene el distrito seleccionado, además de convertirlo a texto ya que por si solo viene como Objeto.

        if (ciudad.equals("")) { // Se valida que la ciudad ingresada no esté vacia, de ser así se muestra un mensaje al usuario.
            JOptionPane.showMessageDialog(null, "Debe ingresar una ciudad", "Ciudad", JOptionPane.WARNING_MESSAGE);
            return; // Se devuelve para que el código no continue avanzando, de no agregar el return pasaria de todas forma a intentar agregar la ciudad. (PD: También se puede lograr envolviendo el try-catch [línea 245 a 266] en un else)
        }

        try {
            int poblacion = Integer.parseInt(txtPoblacion.getText()); // Se obtiene la población ingresada y se convierte a número entero.

            if (poblacion < 0) { // Se valida que no sea menor a 0
                JOptionPane.showMessageDialog(null, "Debe ingresar una cantidad mayor a 0", "Población", JOptionPane.WARNING_MESSAGE);
                return; // Se devuelve para que el código no continue avanzando, de no agregar el return pasaria de todas forma a intentar agregar la ciudad. (PD: También se puede lograr envoviendo la conexión e inserción [línea 253-261] en un else)
            }

            Conector conector = new Conector(); // Se instancia la clase que establece la conexión con la base de datos.

            int filasActualizadas = conector.modificar("INSERT INTO city (Name, CountryCode, District, Population) VALUES (?, 'CHL', ?, ?);", ciudad, distrito, poblacion);

            if (filasActualizadas > 0) { // Se valida que la cantidad de filas actualizadas sea mayor que 0, esto para saber si se agrego la ciudad o no.
                JOptionPane.showMessageDialog(null, "Se ingreso con exito la ciudad", "Resultado", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se ingreso la ciudad", "Resultado", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Inserción de ciudad (SQL ERROR)", JOptionPane.WARNING_MESSAGE);
        } catch (NumberFormatException e) { // Si la población ingresada es un texto, string vacio se lanza una excepción para que el programa no se rompa.
            JOptionPane.showMessageDialog(null, "Ingrese un número válido para la población", "Población", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new App().setVisible(true));
    }

    /**
     * Carga la lista de países y los agrega al combobox cmbPais.
     */
    public final void cargarPaises() { // Función para cargar la lista de países.
        try {
            Conector conector = new Conector(); // Se instancia la clase que establece la conexión con la base de datos.

            ResultSet rs = conector.consultar("SELECT Name FROM Country ORDER BY Name");

            while (rs.next()) { // Recorre los resultados mientra haya datos.
                cmbPais.addItem(rs.getString("Name")); // Añade cada nombre del país al combobox.
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Carga de países (SQL ERROR)", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * Obtiene el código del país seleccionado (por ejemplo, CHL para Chile).
     *
     * @return El código del país seleccionado, o un string vacío si no hay
     * selección o ocurre un error.
     */
    public String obtenerCodigoPais() { // Función para obtener el código del país seleccionado (ej. CHL)
        if (cmbPais.getSelectedItem() == null) { // Se valida que el item en cmbPais no sea nulo por alguna razón, al inicio del programa tal vez.
            return "";
        }

        String pais = cmbPais.getSelectedItem().toString(); // Se obtiene el país seleccionado, además de convertirlo a texto ya que por si solo viene como Objeto.

        try {
            Conector conector = new Conector(); // Se instancia la clase que establece la conexión con la base de datos.

            ResultSet rs = conector.consultar("SELECT Code FROM Country WHERE Name = ?", pais); // Consulta SQL que devuelve el código del país, pasando como argumento el nombre del país.

            if (rs.next()) { // Se verifica si la consulta devolvió datos.
                return rs.getString("Code"); // Retorna el código del país.
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Código de país (SQL ERROR)", JOptionPane.WARNING_MESSAGE);
        }

        return ""; // Por defecto retorna un string vacío.
    }

    /**
     * Carga los distritos de Chile y los agrega al combobox cmbDistrito.
     */
    public final void cargarDistritosCHL() { // Función que carga los distritos de Chile en el combobox cmbDistrito.
        try {
            Conector conector = new Conector(); // Se instancia la clase que establece la conexión con la base de datos.

            ResultSet rs = conector.consultar("SELECT DISTINCT(DISTRICT) FROM city WHERE CountryCode='CHL'");

            while (rs.next()) { // Recorre los resultados mientra haya datos.
                cmbDistrito.addItem(rs.getString("DISTRICT")); // Añade cada nombre del distrito al combobox.
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Carga de distritos (SQL ERROR)", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane JOptionPane;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JComboBox<String> cmbDistrito;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDistrito;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPoblacion;
    private javax.swing.JMenu miArchivo;
    private javax.swing.JMenuItem miConsultar;
    private javax.swing.JMenu miConsultas;
    private javax.swing.JMenuItem miRegistrar;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JPanel pnlConsultar;
    private javax.swing.JPanel pnlRegistrar;
    private javax.swing.JTable tbCiudades;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtPoblacion;
    // End of variables declaration//GEN-END:variables
}
