/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author iryde
 */
import java.sql.*;
import javax.swing.JOptionPane;

public class App extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(App.class.getName());

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane = new javax.swing.JOptionPane();
        Panel = new javax.swing.JPanel();
        lblPais = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblP_Nombre = new javax.swing.JLabel();
        txtP_Nombre = new javax.swing.JTextField();
        lblContinente = new javax.swing.JLabel();
        txtContinente = new javax.swing.JTextField();
        txtRegion = new javax.swing.JTextField();
        lblRegion = new javax.swing.JLabel();
        lblP_Poblacion = new javax.swing.JLabel();
        txtP_Poblacion = new javax.swing.JTextField();
        txtEsperanzaVida = new javax.swing.JTextField();
        lblEsperanzaVida = new javax.swing.JLabel();
        lblDatos = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();
        cmbCiudad = new javax.swing.JComboBox<>();
        lblC_Nombre = new javax.swing.JLabel();
        txtC_Nombre = new javax.swing.JTextField();
        lblC_Poblacion = new javax.swing.JLabel();
        txtC_Poblacion = new javax.swing.JTextField();
        lblIdiomas = new javax.swing.JLabel();
        cmbIdioma = new javax.swing.JComboBox<>();
        lblOficial = new javax.swing.JLabel();
        txtOficial = new javax.swing.JTextField();
        lblPorcHablantes = new javax.swing.JLabel();
        txtPorcHablantes = new javax.swing.JTextField();
        btnP_Modificar = new javax.swing.JButton();
        btnBuscarPais = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPais.setText("País:");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Consulta Geográfica");

        lblP_Nombre.setText("Nombre:");

        txtP_Nombre.setEnabled(false);

        lblContinente.setText("Continente:");

        txtContinente.setEnabled(false);

        txtRegion.setEnabled(false);

        lblRegion.setText("Región:");

        lblP_Poblacion.setText("Población:");

        lblEsperanzaVida.setText("Esperanza de vida:");

        lblDatos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatos.setText("Datos");

        lblCiudad.setText("Ciudad:");

        Separador.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cmbCiudad.addActionListener(this::cmbCiudadActionPerformed);

        lblC_Nombre.setText("Nombre:");

        txtC_Nombre.setEnabled(false);

        lblC_Poblacion.setText("Población");

        txtC_Poblacion.setEnabled(false);

        lblIdiomas.setText("Idiomas:");

        cmbIdioma.addActionListener(this::cmbIdiomaActionPerformed);

        lblOficial.setText("Es oficial:");

        txtOficial.setEnabled(false);

        lblPorcHablantes.setText("% Hablantes:");

        txtPorcHablantes.setEnabled(false);

        btnP_Modificar.setText("Modificar país");
        btnP_Modificar.addActionListener(this::btnP_ModificarActionPerformed);

        btnBuscarPais.setText("Buscar");
        btnBuscarPais.addActionListener(this::btnBuscarPaisActionPerformed);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(lblPais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarPais))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(lblContinente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtContinente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(lblRegion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                                            .addComponent(lblEsperanzaVida)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtEsperanzaVida))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                                            .addComponent(lblP_Poblacion)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtP_Poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(btnP_Modificar))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(lblP_Nombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtP_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(lblCiudad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(lblC_Nombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtC_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(lblC_Poblacion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtC_Poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(lblIdiomas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbIdioma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(lblOficial)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtOficial))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(lblPorcHablantes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPorcHablantes)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarPais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPais)
                        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblP_Nombre)
                            .addComponent(txtP_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCiudad)
                            .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblC_Nombre)
                                    .addComponent(txtC_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblC_Poblacion)
                                    .addComponent(txtC_Poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIdiomas)
                                    .addComponent(cmbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblOficial)
                                    .addComponent(txtOficial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPorcHablantes)
                                    .addComponent(txtPorcHablantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblContinente)
                                    .addComponent(txtContinente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRegion)
                                    .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblP_Poblacion)
                                    .addComponent(txtP_Poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEsperanzaVida)
                                    .addComponent(txtEsperanzaVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(btnP_Modificar)
                                .addGap(20, 20, 20))))
                    .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnP_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP_ModificarActionPerformed

        ConectorBD conector = null; // Se declara nula para poder usarla en el finally, permitiendo cerrar la conexión.

        try {
            String pais = txtP_Nombre.getText(); // Obtiene el nombre del país, ya que este no se modifica da lo mismo obtenerlo de acá

            int poblacionPais = Integer.parseInt(txtP_Poblacion.getText());
            double esperanzaVidaPais = Double.parseDouble(txtEsperanzaVida.getText());

            if (poblacionPais <= 0) {
                JOptionPane.showMessageDialog(null, "Debe ingresar una población mayor a 0.");
                return;
            }

            if (esperanzaVidaPais < 1.0 || esperanzaVidaPais > 89.9) {
                JOptionPane.showMessageDialog(null, "Debe ingresar una esperanza de vida entre 1.0 y 89.9.");
                return;
            }
            
            conector = new ConectorBD();

            int cant = conector.modificar("UPDATE country SET Population = ?, LifeExpectancy = ? WHERE NAME = ?", poblacionPais, esperanzaVidaPais, pais);

            if (cant > 0) {
                JOptionPane.showMessageDialog(null, "Se modificó el registro.");
            } else {
                JOptionPane.showMessageDialog(null, "No hubo cambios.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese numeros válidos");
        } finally {
            try {
                if (conector != null) { // Verifica si el conector no es nulo.
                    conector.close(); // Cierra la conexión, se ejecutará siempre independiente si pasó por una excepción o no.
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnP_ModificarActionPerformed

    private void btnBuscarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPaisActionPerformed
        String busquedaPais = txtPais.getText();

        ConectorBD conector = null;

        try {
            conector = new ConectorBD();

            ResultSet rs = conector.consultar("SELECT Name, Continent, Region, Population, LifeExpectancy, Code FROM country WHERE LOWER(Name) LIKE ? LIMIT 1", busquedaPais.toLowerCase() + "%");

            if (rs.next()) {
                txtP_Nombre.setText(rs.getString("Name"));
                txtContinente.setText(rs.getString("Continent"));
                txtRegion.setText(rs.getString("Region"));
                txtP_Poblacion.setText(rs.getString("Population"));
                txtEsperanzaVida.setText(rs.getString("LifeExpectancy"));

                cargarCiudades(rs.getString("Code"));
                cargarIdiomas(rs.getString("Code"));
            } else {
                JOptionPane.showMessageDialog(null, "País no encontrado");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (conector != null) {
                    conector.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnBuscarPaisActionPerformed

    private void cmbCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCiudadActionPerformed
        if (cmbCiudad.getSelectedItem() == null) {
            return;
        }

        String ciudad = cmbCiudad.getSelectedItem().toString();

        ConectorBD conector = null;

        try {
            conector = new ConectorBD();

            ResultSet rs = conector.consultar("SELECT Name, Population FROM city WHERE Name = ?", ciudad);

            if (rs.next()) {
                txtC_Nombre.setText(rs.getString("Name"));
                txtC_Poblacion.setText(rs.getString("Population"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (conector != null) {
                    conector.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_cmbCiudadActionPerformed
    
    String codigoPais; // Variable global, sirve para filtrar despúes por el código del país los idiomas.
    private void cmbIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdiomaActionPerformed
        if (cmbIdioma.getSelectedItem() == null) {
            return;
        }

        String idioma = cmbIdioma.getSelectedItem().toString();

        ConectorBD conector = null;

        try {
            conector = new ConectorBD();

            ResultSet rs = conector.consultar("SELECT IsOfficial, Percentage FROM countrylanguage WHERE Language = ? AND Countrycode = ?", idioma, codigoPais);

            if (rs.next()) {
                txtOficial.setText(rs.getString("IsOfficial").equals("T") ? "Sí" : "No");
                txtPorcHablantes.setText(String.format("%.2f", rs.getDouble("Percentage")));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (conector != null) {
                    conector.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_cmbIdiomaActionPerformed

    private void cargarCiudades(String countryCode) { // Toma como parametro el código del país para mostrar las ciudades de solo el país ingresado.
        ConectorBD conector = null;

        try {
            conector = new ConectorBD();

            ResultSet rs = conector.consultar("SELECT Name, Population FROM city WHERE CountryCode = ? ORDER BY Population DESC", countryCode);

            cmbCiudad.removeAllItems();

            while (rs.next()) {
                cmbCiudad.addItem(rs.getString("Name"));
            }

            if (cmbCiudad.getItemCount() == 0) { // Si despúes de recorrer las filas y no agregar nada al comboBox es porque no hay ciudades dentro del país.
                JOptionPane.showMessageDialog(null, "Sin ciudades registradas.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (conector != null) {
                    conector.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }

    private void cargarIdiomas(String countryCode) { // Toma como parametro el código del país para mostrar los idiomas de solo el país ingresado.
        ConectorBD conector = null;
        codigoPais = countryCode;

        try {
            conector = new ConectorBD();

            ResultSet rs = conector.consultar("SELECT Language FROM countrylanguage WHERE CountryCode = ?", countryCode);

            cmbIdioma.removeAllItems();

            while (rs.next()) {
                cmbIdioma.addItem(rs.getString("Language"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (conector != null) {
                    conector.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new App().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JSeparator Separador;
    private javax.swing.JButton btnBuscarPais;
    private javax.swing.JButton btnP_Modificar;
    private javax.swing.JComboBox<String> cmbCiudad;
    private javax.swing.JComboBox<String> cmbIdioma;
    private javax.swing.JOptionPane jOptionPane;
    private javax.swing.JLabel lblC_Nombre;
    private javax.swing.JLabel lblC_Poblacion;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblContinente;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblEsperanzaVida;
    private javax.swing.JLabel lblIdiomas;
    private javax.swing.JLabel lblOficial;
    private javax.swing.JLabel lblP_Nombre;
    private javax.swing.JLabel lblP_Poblacion;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPorcHablantes;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtC_Nombre;
    private javax.swing.JTextField txtC_Poblacion;
    private javax.swing.JTextField txtContinente;
    private javax.swing.JTextField txtEsperanzaVida;
    private javax.swing.JTextField txtOficial;
    private javax.swing.JTextField txtP_Nombre;
    private javax.swing.JTextField txtP_Poblacion;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPorcHablantes;
    private javax.swing.JTextField txtRegion;
    // End of variables declaration//GEN-END:variables
}
