
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author iryde
 */
public class AppPropina extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppPropina.class.getName());

    /**
     * Creates new form AppPropina
     */
    public AppPropina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OptionPane = new javax.swing.JOptionPane();
        mainPanel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblPorcentaje = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        lblNumPersonas = new javax.swing.JLabel();
        txtNumPersonas = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcula Propina");

        mainPanel.setBackground(new java.awt.Color(0, 102, 0));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Calcula Propina");
        lblTitulo.setToolTipText("");

        lblTotal.setText("Total cuenta:");

        lblPorcentaje.setText("Porcentaje propina:");

        lblNumPersonas.setText("Número de personas:");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(97, 97, 97))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(lblPorcentaje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(lblNumPersonas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblTitulo)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(39, 39, 39)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumPersonas))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {
            double totalCuenta = Double.parseDouble(txtTotal.getText());
            double porcentajePropina = Double.parseDouble(txtPorcentaje.getText());
            int numPersonas = Integer.parseInt(txtNumPersonas.getText());

            if (totalCuenta <= 0) {
                JOptionPane.showMessageDialog(null, "El total de la cuenta debe ser mayor a 0.", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (porcentajePropina <= 0) {
                JOptionPane.showMessageDialog(null, "El porcentaje de propina debe ser mayor a 0.", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (numPersonas <= 0) {
                JOptionPane.showMessageDialog(null, "El número de personas debe ser mayor a 0.", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Propina propina = new Propina(totalCuenta, porcentajePropina, numPersonas);

            double pagoPorPersona = propina.calcularPagoPorPersona();

            if (pagoPorPersona <= 5000) {
                JOptionPane.showMessageDialog(null, "Cuenta accesible. Cada persona paga $" + pagoPorPersona, "Propina", JOptionPane.INFORMATION_MESSAGE);
            } else if (pagoPorPersona <= 15000) {
                JOptionPane.showMessageDialog(null, "Cuenta moderada. Cada persona paga $" + pagoPorPersona, "Propina", JOptionPane.INFORMATION_MESSAGE);
            } else if (pagoPorPersona > 15000) {
                JOptionPane.showMessageDialog(null, "Cuenta elevada. Cada persona paga $" + pagoPorPersona, "Propina", JOptionPane.INFORMATION_MESSAGE);

                // Se hace uso de un do-while para poder preguntar la cantidad de personas hasta que se cumpla la condición (x > 0)
                int nuevoNumPersonas = 0;

                do {
                    String respuestaPersonas = JOptionPane.showInputDialog("Ingrese nuevo de personas:");

                    if (respuestaPersonas == null) {
                        return;
                    }

                    nuevoNumPersonas = Integer.parseInt(respuestaPersonas);

                    if (nuevoNumPersonas <= 0) {
                        JOptionPane.showMessageDialog(null, "El número de personas debe ser mayor a 0.", "", JOptionPane.INFORMATION_MESSAGE);
                    }
                } while (nuevoNumPersonas <= 0);

                propina.setNum_personas(nuevoNumPersonas);
                double nuevoPago = propina.calcularPagoPorPersona();

                JOptionPane.showMessageDialog(null, "Con " + nuevoNumPersonas + " personas, cada una pagaría $" + nuevoPago, "Propina", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese números válidos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppPropina().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane OptionPane;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblNumPersonas;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtNumPersonas;
    private javax.swing.JTextField txtPorcentaje;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
