
import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author iryde
 */
public class AppEjemplo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppEjemplo.class.getName());

    /**
     * Creates new form AppEjemplo
     */
    public AppEjemplo() {
        initComponents();
        cargarPaises(cmbP_Pais);
        cargarPaises(cmbC_Pais);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JOptionPane = new javax.swing.JOptionPane();
        TabbedPane = new javax.swing.JTabbedPane();
        pnPais = new javax.swing.JPanel();
        lblP_Titulo = new javax.swing.JLabel();
        lblP_Pais = new javax.swing.JLabel();
        cmbP_Pais = new javax.swing.JComboBox<>();
        btnP_Modificar = new javax.swing.JButton();
        lblP_GNP = new javax.swing.JLabel();
        txtP_GNP = new javax.swing.JTextField();
        txtP_GNPOld = new javax.swing.JTextField();
        lblP_GNPOld = new javax.swing.JLabel();
        pnCiudad = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        tbC_Tabla = new javax.swing.JTable();
        lblC_Pais = new javax.swing.JLabel();
        cmbC_Pais = new javax.swing.JComboBox<>();
        lblC_Ciudad = new javax.swing.JLabel();
        cmbC_Ciudad = new javax.swing.JComboBox<>();
        pnIdioma = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblP_Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblP_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblP_Titulo.setText("Actualiza PIB");

        lblP_Pais.setText("País:");

        cmbP_Pais.addActionListener(this::cmbP_PaisActionPerformed);

        btnP_Modificar.setText("Modificar GNP");
        btnP_Modificar.addActionListener(this::btnP_ModificarActionPerformed);

        lblP_GNP.setText("GNP Actual:");

        txtP_GNPOld.setEnabled(false);

        lblP_GNPOld.setText("GNP Antiguo:");

        javax.swing.GroupLayout pnPaisLayout = new javax.swing.GroupLayout(pnPais);
        pnPais.setLayout(pnPaisLayout);
        pnPaisLayout.setHorizontalGroup(
            pnPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblP_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPaisLayout.createSequentialGroup()
                .addGroup(pnPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnPaisLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblP_Pais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbP_Pais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnPaisLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(pnPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPaisLayout.createSequentialGroup()
                                .addComponent(lblP_GNPOld)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtP_GNPOld, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                            .addGroup(pnPaisLayout.createSequentialGroup()
                                .addComponent(lblP_GNP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtP_GNP)))))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPaisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnP_Modificar)
                .addGap(143, 143, 143))
        );
        pnPaisLayout.setVerticalGroup(
            pnPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblP_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP_Pais)
                    .addComponent(cmbP_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP_GNP)
                    .addComponent(txtP_GNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP_GNPOld)
                    .addComponent(txtP_GNPOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnP_Modificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Mantenedor País", pnPais);

        tbC_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPane.setViewportView(tbC_Tabla);

        lblC_Pais.setText("País:");

        cmbC_Pais.addActionListener(this::cmbC_PaisActionPerformed);

        lblC_Ciudad.setText("Ciudad:");

        javax.swing.GroupLayout pnCiudadLayout = new javax.swing.GroupLayout(pnCiudad);
        pnCiudad.setLayout(pnCiudadLayout);
        pnCiudadLayout.setHorizontalGroup(
            pnCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnCiudadLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblC_Pais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbC_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(lblC_Ciudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbC_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        pnCiudadLayout.setVerticalGroup(
            pnCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblC_Ciudad)
                        .addComponent(cmbC_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblC_Pais)
                        .addComponent(cmbC_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab("Mantenedor Ciudades", pnCiudad);

        javax.swing.GroupLayout pnIdiomaLayout = new javax.swing.GroupLayout(pnIdioma);
        pnIdioma.setLayout(pnIdiomaLayout);
        pnIdiomaLayout.setHorizontalGroup(
            pnIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnIdiomaLayout.setVerticalGroup(
            pnIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Mantenedor Idiomas", pnIdioma);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Mantenedor País
    private void cmbP_PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbP_PaisActionPerformed
        cargarDatosPais();
    }//GEN-LAST:event_cmbP_PaisActionPerformed

    private void btnP_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP_ModificarActionPerformed
        if (cmbP_Pais.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "No hay un país seleccionado", "Modificación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String pais = cmbP_Pais.getSelectedItem().toString();

        try {
            float gnp = Float.parseFloat(txtP_GNP.getText());

            if (gnp < 1) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un GNP mayor a 0.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Conector conector = new Conector();

            int cant = conector.modificar("UPDATE country SET GNPOld = GNP, GNP = ? WHERE Name = ?;", gnp, pais);

            if (cant > 0) {
                JOptionPane.showMessageDialog(null, "El GNP fue actualizado exitosamente.", "Modificación", JOptionPane.INFORMATION_MESSAGE);

                cargarDatosPais();
            } else {
                JOptionPane.showMessageDialog(null, "El GNP no fue actualizado.", "Modificación", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "SQL ERROR", JOptionPane.WARNING_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido", "Formato", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnP_ModificarActionPerformed

    private void cargarDatosPais() {
        if (cmbP_Pais.getSelectedItem() == null) {
            return;
        }

        String pais = cmbP_Pais.getSelectedItem().toString();

        try {
            Conector conector = new Conector();

            ResultSet rs = conector.consultar("SELECT GNP, GNPOld FROM country WHERE Name = ?", pais);

            if (rs.next()) {
                txtP_GNP.setText(rs.getString("GNP"));
                txtP_GNPOld.setText(rs.getString("GNPOld"));
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron resultados para el país seleccionado.", "Carga datos", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "SQL ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    // Mantenedor ciudades
    private void cmbC_PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbC_PaisActionPerformed
        cmbC_Ciudad.removeAllItems();
        
        try {
            Conector conector = new Conector();
            
            String pais = cmbC_Pais.getSelectedItem().toString();
            
            ResultSet rs = conector.consultar("SELECT c.Name FROM city c JOIN country ct ON(c.CountryCode = ct.Code) WHERE ct.Name  = ?", pais);
            
            while (rs.next()) {
                cmbC_Ciudad.addItem(rs.getString("Name"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "SQL ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmbC_PaisActionPerformed

    private void cargarTabla() {
        DefaultTableModel mt = new DefaultTableModel();

        String encabezados[] = {"Pais", "Ciudad", "Población"};

        mt.setColumnIdentifiers(encabezados);

        tbC_Tabla.setModel(mt);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppEjemplo().setVisible(true));
    }

    private void cargarPaises(JComboBox<String> componente) {
        try {
            Conector conector = new Conector();

            ResultSet rs = conector.consultar("SELECT Name FROM country ORDER BY Name");

            while (rs.next()) {
                componente.addItem(rs.getString("Name"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "SQL ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane JOptionPane;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton btnP_Modificar;
    private javax.swing.JComboBox<String> cmbC_Ciudad;
    private javax.swing.JComboBox<String> cmbC_Pais;
    private javax.swing.JComboBox<String> cmbP_Pais;
    private javax.swing.JLabel lblC_Ciudad;
    private javax.swing.JLabel lblC_Pais;
    private javax.swing.JLabel lblP_GNP;
    private javax.swing.JLabel lblP_GNPOld;
    private javax.swing.JLabel lblP_Pais;
    private javax.swing.JLabel lblP_Titulo;
    private javax.swing.JPanel pnCiudad;
    private javax.swing.JPanel pnIdioma;
    private javax.swing.JPanel pnPais;
    private javax.swing.JTable tbC_Tabla;
    private javax.swing.JTextField txtP_GNP;
    private javax.swing.JTextField txtP_GNPOld;
    // End of variables declaration//GEN-END:variables
}
