
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author iryde
 */
public class AppBono extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppBono.class.getName());

    /**
     * Creates new form AppBono
     */
    public AppBono() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane = new javax.swing.JOptionPane();
        mainPanel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblVentasRealizadas = new javax.swing.JLabel();
        txtVentasRealizadas = new javax.swing.JTextField();
        lblMetaVentas = new javax.swing.JLabel();
        txtMetaVentas = new javax.swing.JTextField();
        txtSueldoBase = new javax.swing.JTextField();
        lblSueldoBase = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcula Bono");

        mainPanel.setBackground(java.awt.Color.orange);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Calcula Bono");

        lblVentasRealizadas.setForeground(new java.awt.Color(0, 0, 0));
        lblVentasRealizadas.setText("Ventas realizadas:");

        lblMetaVentas.setForeground(new java.awt.Color(0, 0, 0));
        lblMetaVentas.setText("Meta de ventas:");

        lblSueldoBase.setForeground(new java.awt.Color(0, 0, 0));
        lblSueldoBase.setText("Sueldo base:");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(104, 104, 104))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(lblSueldoBase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(lblMetaVentas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMetaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(lblVentasRealizadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVentasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnCalcular)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVentasRealizadas)
                    .addComponent(txtVentasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetaVentas)
                    .addComponent(txtMetaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSueldoBase)
                    .addComponent(txtSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {
            double ventasRealizadas = Double.parseDouble(txtVentasRealizadas.getText());
            double metaVentas = Double.parseDouble(txtMetaVentas.getText());
            double sueldoBase = Double.parseDouble(txtSueldoBase.getText());

            if (ventasRealizadas <= 0) {
                JOptionPane.showMessageDialog(null, "La ventas realizadas deben ser mayores a $0.");
                return;
            }

            if (metaVentas <= 0) {
                JOptionPane.showMessageDialog(null, "La meta de ventas debe ser mayor a $0.");
                return;
            }

            if (sueldoBase <= 0) {
                JOptionPane.showMessageDialog(null, "El sueldo base debe ser mayor a $0.");
                return;
            }

            Bono bono_ = new Bono(ventasRealizadas, metaVentas, sueldoBase);

            double diferencia = bono_.calcularDiferencia();
            double bono = bono_.calcularBono();
            double sueldoFinal = bono_.calcularSueldoFinal(bono);

            if (diferencia > 0) {
                JOptionPane.showMessageDialog(null, "¡Superaste la meta! Tu bono es $" + bono + ". Tu sueldo final es $" + sueldoFinal + ".");
            } else if (diferencia == 0) {
                JOptionPane.showMessageDialog(null, "Alcanzaste la meta exacta. Tu bono es $" + bono + ". Tu sueldo final es $" + sueldoFinal + ".");
            } else if (diferencia < 0) {
                JOptionPane.showMessageDialog(null, "No alcanzaste la meta. Te faltaron $" + (diferencia * -1) + " en ventas.");

                double ventasAdicionales = -1;

                do {
                    try {
                        String opcion = JOptionPane.showInputDialog(null, "Ingrese un monto adicional de ventas:");

                        if (opcion == null) {
                            return;
                        }

                        ventasAdicionales = Double.parseDouble(opcion);

                        if (ventasAdicionales < 0) {
                            JOptionPane.showMessageDialog(null, "Las ventas adicionales no pueden ser menores a $0.");
                            ventasAdicionales = -1;
                        }
                    } catch(NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Ingrese un número válido", "Formato inválido", JOptionPane.WARNING_MESSAGE);
                    }
                } while (ventasAdicionales < 0);

                double ventasTotales = bono_.calcularVentasAdicionales(ventasAdicionales);
                bono_.setVentasRealizadas(ventasTotales);

                if (ventasTotales >= metaVentas) {
                    double nuevoBono = bono_.calcularBono();

                    JOptionPane.showMessageDialog(null, "Con ese aumento alcanzarías la meta. Tu bono sería $" + nuevoBono);
                } else if (ventasTotales < metaVentas) {
                    double nuevaDiferencia = bono_.calcularDiferencia();
                    JOptionPane.showMessageDialog(null, "Aún no alcanzas la meta. Te seguirían faltando $" + (nuevaDiferencia * -1));
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido", "Formato inválido", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppBono().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JOptionPane jOptionPane;
    private javax.swing.JLabel lblMetaVentas;
    private javax.swing.JLabel lblSueldoBase;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVentasRealizadas;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtMetaVentas;
    private javax.swing.JTextField txtSueldoBase;
    private javax.swing.JTextField txtVentasRealizadas;
    // End of variables declaration//GEN-END:variables
}
